### ISSUE TITLE
Failed to connect to localhost port 8080: Connection refused

### ISSUE THREAD

**Issue by nanahpang** [xstefank/eventuate-service#4]
Hi, I follow the process in readme and when I try 
curl -X POST -H "Content-Type: application/json" -d '{"productId":"testProduct", "comment":"testComment", "price":"20"}' http://localhost:8080/api/order 
it responds failed to connect.
I wonder how you set up your IP, since the sample in eventuate says you should not use localhost as DOCKER_HOST_IP. 
Thanks.

**Comment by xstefank** [comment]
Hello @nanahpang,

thanks for checking this!

It looks like that your order-service is not started, but I would need more information (copy-paste the error) 

Try please:
* `docker ps` - does it show order-service?
* `docker container logs eventuate_service_order-service_1` (or similar name, I am not running it now) -- does it show any errors?

**Comment by nanahpang** [comment]
- docker ps has oerder-service, but it gives warning when I run "docker-compose up -d --build". 
WARNING: The DOCKER_HOST_IP variable is not set. Defaulting to a blank string. 
Is this warning causing issue? because the port info of order service is 0.0.0.0:8080
7e51353f12ac        eventuateservice_order-service                     "/bin/sh -c 'java ..."   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp                                                   eventuateservice_order-service_1

- container log has several errors, I paste the whole log file and some lines error locates:
[order_service.txt](https://github.com/xstefank/eventuate-service/files/1900523/order_service.txt)

1. {"log":"2018-04-11 20:34:52.978 ERROR 6 --- [           main] i.e.l.j.k.c.EventuateKafkaConsumer       : Got exception: \n","stream":"stdout","time":"2018-04-11T20:34:53.084842549Z"}
2. {"log":"2018-04-11 20:34:53.059 ERROR 6 --- [           main] i.e.l.j.k.c.EventuateKafkaConsumer       : Error subscribing\n","stream":"stdout","time":"2018-04-11T20:34:53.085482343Z"}
3. {"log":"2018-04-11 20:34:53.151  WARN 6 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sagaEventSubscriber' defined in URL [jar:file:/order-service-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/org/learn/eventuate/orderservice/saga/SagaEventSubscriber.class]: Initialization of bean failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata\n","stream":"stdout","time":"2018-04-11T20:34:53.15226147Z"}
4. {"log":"Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.\n","stream":"stdout","time":"2018-04-11T20:34:56.125162975Z"}
{"log":"2018-04-11 20:34:56.172 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application startup failed\n","stream":"stdout","time":"2018-04-11T20:34:56.172767731Z"}
{"log":"\n","stream":"stdout","time":"2018-04-11T20:34:56.172795829Z"}
{"log":"org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sagaEventSubscriber' defined in URL [jar:file:/order-service-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/org/learn/eventuate/orderservice/saga/SagaEventSubscriber.class]: Initialization of bean failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata\n","stream":"stdout","time":"2018-04-11T20:34:56.17279931Z"}
Thanks.

**Comment by xstefank** [comment]
the warning shouldn't really cause an issue, but you can set it for the host where your docker is running - if you're running on local machine, this needs to be machine IP, not the localhost (127.0.0.1)

However, the error looks like is in the Kafka which is provided by Eventuate, can you check that service? again if it's running please copy-paste the error

**Comment by nanahpang** [comment]
Hello @xstefank  Thanks for your response. I check the log in Kafka and find following errors:
1. [2018-04-12 10:50:35,788] INFO Socket connection established to eventuateservice_zookeeper_1.eventuateservice_default/172.18.0.3:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-04-12 10:50:41,588] INFO Client session timed out, have not heard from server in 7571ms for sessionid 0x162b9780b6c0002, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-04-12 10:50:45,645] INFO Opening socket connection to server eventuateservice_zookeeper_1.eventuateservice_default/172.18.0.3:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
2. [2018-04-12 10:52:05,857] ERROR [KafkaApi-0] Error when handling request {topics=[org.learn.eventuate.shipmentservice.domain.ShipmentAggregate]} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:670)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:666)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:93)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:666)
	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:727)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:79)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2018-04-12 10:52:07,236] ERROR [KafkaApi-0] Error when handling request {topics=[org.learn.eventuate.shipmentservice.domain.ShipmentAggregate]} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:670)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:666)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:93)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:666)
	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:727)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:79)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
3. [2018-04-12 10:56:39,864] ERROR [KafkaApi-0] Error when handling request {topics=[eventuate.local.cdc.my-sql-connector.offset.storage]} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:670)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:666)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:93)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:666)
	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:727)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:79)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
I paste the log file below. Thanks
[Kaffka.log](https://github.com/xstefank/eventuate-service/files/1902927/Kaffka.log)

**Comment by xstefank** [comment]
Hello @nanahpang,

I would say, you need to follow further, try zookeeper, these services are provided by Eventuate platform. Maybe you can try to run some of their examples? Nevertheless, you can post here logs from zookeeper, in case of error
